apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s: 
      volumeClaimTemplate:
        spec:
          storageClassName: thin
          volumeMode: Filesystem
          resources:
            requests:
              storage: 40Gi
      externalLabels:
        i0000000:0000001
        cluster_id: ocp4
        i0000001:0000001
    enableUserWorkerload: true
