kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-self-provisioners-crb
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: service-accounts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-provisioner