kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'gitops-repo-server-privileged-rb'
  namespace: openshift-gitops
subjects:
  - kind: ServiceAccount
    name: default
    namespace: openshift-gitops 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
